title: Sara Talks
subtitle: Oi! Seja Bem-vindo ğŸ‘‹ğŸ»
description: ExperiÃªncias de uma engenheira que te um pÃ© na computaÃ§Ã£o e outro no mundo.
url: "http://saralonngren.github.io"

author:
  name: Sara Lonngren
  email: saralonngren@gmail.com
  bio: Sou desenvolvedora backend diretamente do cearÃ¡! Viciada em chÃ¡ preto com leite, interessada em educaÃ§Ã£o, jogos, minimalismo, inovaÃ§Ã£o, tecnologia, pessoas e design.
  # img: /assets/img/perfil.jpg

# Build settings
markdown: kramdown
permalink: /:categories/:title/ # ConfiguraÃ§Ã£o dos links do blog

plugins:
  - jekyll-feed
  - jemoji

minima:
  social_links:
    twitter: saralonngren
    github: saralonngren
    linkedin: saralonngren

reading_time:
  second_plural: "segundos"    # default: seconds
  minute_singular: "min de leitura"  # default: minute
  minute_plural: "min de leitura"    # default: minutes

header_pages:
  - about.md
