title: Sara Talks
subtitle: Oi! Seja Bem-vindo ğŸ‘‹ğŸ»
description: ExperiÃªncias de uma engenheira que te um pÃ© na computaÃ§Ã£o e outro no mundo.
url: "http://saralonngren.github.io"

author:
  name: Sara Lonngren
  # img: /assets/img/perfil.jpg
  email: saralonngren@gmail.com
  twitter: saralonngren
  github: saralonngren
  bio: Sou desenvolvedora backend diretamente do cearÃ¡! Viciada em chÃ¡ preto com leite, interessada em educaÃ§Ã£o, jogos, minimalismo, inovaÃ§Ã£o, tecnologia, pessoas e design.

# Build settings
markdown: kramdown
permalink: /:categories/:title/ # ConfiguraÃ§Ã£o dos links do blog
plugins:
  - jekyll-feed

